print("Hello World")
print("All is well")
print("Health is wealth")
print("Hello World")
print("All is well")
print("Health is wealth")
print("Hello World")
print("All is well")
print("Health is wealth")
